# genk8s:hash=9d6325d87afa358ab9c4178aff0b239d
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tax-receipts-app
  labels:
    app: tax-receipts-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tax-receipts
  template:
    metadata:
      labels:
        app: tax-receipts
    spec:
      volumes:
      - name: data
        configMap:
          name: tax-receipts-nginx
      containers:
      - name: api
        imagePullPolicy: Always
        image: northamerica-northeast2-docker.pkg.dev/gpo-eng-stage/gpo/tax-receipts-api:staging
        envFrom:
        - configMapRef:
            name: tax-receipts-env
        - secretRef:
            name: tax-receipts-session
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: tax-receipts-app
              key: uri
        - name: TRUST_PROXY
          value: "true"
        - name: PUBLIC_WEB_URL
          value: "https://tax.gpotoolsstage.ca"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
      - name: web
        image: northamerica-northeast2-docker.pkg.dev/gpo-eng-stage/gpo/tax-receipts-web:staging
        env:
        - name: API_UPSTREAM
          value: http://localhost:3000
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
