apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: tax-receipts-session
  namespace: tax-receipts
spec:
  length: 32
  symbols: 0
---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tax-receipts-session
  namespace: tax-receipts
spec:
  refreshPolicy: CreatedOnce
  target:
    template:
      data:
        SESSION_SECRET: "{{ .password }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: tax-receipts-session
