apiVersion: v1
kind: Service
metadata:
  name: tax-receipts
  labels:
    app: tax-receipts
spec:
  selector:
    app: tax-receipts
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
