apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: canopy-db
  namespace: canopy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  target:
    name: canopy-db
  dataFrom:
  - extract:
      key: canopy-db
