# genk8s:hash=5699ac5ff5dc9d0f337bfbded1fa287a
apiVersion: v1
data:
  WP_ENV: stage
  WP_HOME: https://canopy.gpogear.ca
  WP_SITEURL: https://canopy.gpogear.ca/wp
kind: ConfigMap
metadata:
  annotations:
  labels:
    app: canopy
  name: canopy
  namespace: canopy
