# genk8s:hash=ac2296a6d5d75dac793a9cd6b74d86cc
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: canopy
  namespace: canopy
  labels:
    gateway: gpogear
spec:
  # this connects us to the gateway
  parentRefs:
  - kind: Gateway
    name: gpogear
    namespace: gateway
    sectionName: tls-gear
  hostnames:
  - "canopy.gpogear.ca"
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: canopy
      port: 8080
