# genk8s:hash=83e064d7a8e579bc3c3e3e7f3bf07edd
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: canopy@gpo-eng-stage.iam.gserviceaccount.com
  name: canopy
  namespace: canopy
