# genk8s:hash=d4b862e8ccb660c3ae5bbb37bc79e83e
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-gpotools
  namespace: gateway
spec:
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns-prod
  secretName: wildcard-gpotools
  dnsNames:
  - "*.gpotoolsstage.ca"

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-gpogear
  namespace: gateway
spec:
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns-prod
  secretName: wildcard-gpogear
  dnsNames:
  - "*.gpogear.ca"
