# genk8s:hash=a43d8bea9a44674116a6fc1ef4aef2ca
# +argocd:skip-file-rendering
global:
  domain: argocd.gpotoolsstage.ca

configs:
  params:
    server.insecure: true
  cm:
    accounts.rsalmond: "apiKey, login"

server:
  httproute:
    enabled: true
    hostnames: ["argocd.gpotoolsstage.ca"]
    parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gpotools
      namespace: gateway
      sectionName: tls_tools

dex:
  enabled: false
