# genk8s:hash=ca71370beb14b2e2d6d9156b28c9945a
# +argocd:skip-file-rendering
global:
  domain: argocd.gpotoolsstage.ca

configs:
  params:
    server.insecure: true
  cm:
    accounts.rsalmond: "apiKey, login"

server:
  httproute:
    enabled: true
    hostnames: ["argocd.gpotoolsstage.ca"]
    parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gpotools
      namespace: gateway
      sectionName: tls-tools

dex:
  enabled: false
